parent:
    github:         hiqdev/hidev-config

package:
    name:           yii2-collection
    namespace:      hiqdev\collection
    label:          CollectionLibrary
    title:          Collection Library for Yii2
    type:           yii2-extension
    keywords:       collection, extension, yii2
    year:           2015

composer.json:
    require-dev:
        yiisoft/yii2:               "~2.0"
        yiisoft/yii2-codeception:   "~2.0"
