package:
    name:           yii2-collection
    namespace:      hiqdev\collection
    label:          CollectionLibrary
    title:          Collection Library for Yii2
    type:           yii2-extension
    keywords:       collection, extension, yii2
    year:           2015

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
